# Generated by Django 4.2.19 on 2025-03-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='publisher',
            new_name='shared_by',
        ),
        migrations.RemoveField(
            model_name='share',
            name='sharedwith',
        ),
        migrations.AddField(
            model_name='share',
            name='shared_with',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
