# Generated by Django 4.2.19 on 2025-03-22 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0002_rename_publisher_upload_shared_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='filepath',
            field=models.FileField(upload_to=''),
        ),
    ]
