# Generated by Django 4.2.19 on 2025-03-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0003_alter_upload_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='filetype',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
