# Generated by Django 5.1.4 on 2025-04-16 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0004_upload_filetype'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='username',
        ),
        migrations.AddField(
            model_name='userdata',
            name='displayed_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='share',
            name='shared_with',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
