# Generated by Django 5.1.4 on 2025-04-16 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharedoc', '0005_remove_userdata_username_userdata_displayed_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='share',
            name='shared_with',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to='sharedoc.userdata'),
        ),
    ]
